-- AlterTable
ALTER TABLE "EmergencyDetails" ALTER COLUMN "phone1" SET DATA TYPE TEXT,
ALTER COLUMN "phone2" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Owner" ALTER COLUMN "phone1" SET DATA TYPE TEXT,
ALTER COLUMN "phone2" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Renter" ALTER COLUMN "phone1" SET DATA TYPE TEXT,
ALTER COLUMN "phone2" SET DATA TYPE TEXT;
